version: "3"

networks:
   monitor:
     driver: bridge

services:
  prometheus:
    image: prom/prometheus:latest
    hostname: prometheus
    restart: always
    volumes:
      - /opt/monitor/prometheus:/prometheus
    command: "--web.external-url=http://192.168.99.222:9090 --config.file=/prometheus/prometheus.yml --web.enable-lifecycle"
    ports:
      - 9090:9090
    depends_on:
      - exporter
    networks:
      - monitor

  exporter:
    build:
      context: node_exporter
      dockerfile: Dockerfile
    image: node_exporter
    hostname: node_exporter
    restart: always
    ports:
      - "9100:9100"
    volumes:
      - /opt/monitor/fil:/path:rw
    networks:
      - monitor

  grafana:
    image: grafana/grafana
    hostname: grafana
    ports:
      - "3000:3000"
    restart: always
    volumes:
      - /opt/monitor/grafana:/var/lib/grafana
      - /etc/localtime:/etc/localtime
    depends_on:
      - prometheus
    networks:
      - monitor

  alertmanager:
    image: prom/alertmanager
    hostname: alertmanager
    restart: always
    volumes:
      - /opt/prometheus/alertmanager/alertmanager.yml:/usr/local/alertmanager/alertmanager.yml
      - /opt/prometheus/alertmanager/template:/usr/local/alertmanager/template
    ports:
      - "9093:9093"
    networks:
      - monitor
